### ISSUE TITLE
PCのメニュー部分をスクロール時に上部固定にする

### ISSUE THREAD

**Issue by HiroyukiYahagi** [todoroki00/bunkin#14]

**Comment by daisuke-san** [comment]
修正内容
https://github.com/todoroki00/bunkin/commit/f875ab10a613c09eeb3ef403286a9a2eee0a8cbb

**Comment by daisuke-san** [comment]
レスポンシブが効いてなかったので
https://github.com/todoroki00/bunkin/commit/248e3521c4de32da019cd571eb3002493a0c9be9
