### ISSUE TITLE
トップの写真に重なった文字を大きくする/詳細はこちらの文言をつける

### ISSUE THREAD

**Issue by HiroyukiYahagi** [todoroki00/bunkin#16]

**Comment by daisuke-san** [comment]
修正内容
https://github.com/todoroki00/bunkin/commit/7e1047d8ca08b86653c5460c66783d9637316089

**Comment by daisuke-san** [comment]
レスポンシブ
https://github.com/todoroki00/bunkin/commit/7bc70db045e6604547bdc248d7622b1c0dcc124b
