### ISSUE TITLE
各種届出用紙のリスト表示に画像を出す

### ISSUE THREAD

**Issue by HiroyukiYahagi** [todoroki00/bunkin#22]
JPG表示されている各種届出用紙の下部にダウンロードボタンを置く |

各種届出用紙がダウンロードできるのであれば「ワード版はこちらから」と並列でリンク（ボタン）をおたほうがわかりやすいかと思いました。

**Comment by daisuke-san** [comment]
下記のwordpress管理画面から修正
・リンクをボタンに
・画像をセンタリング
・複数ダウンロード方法がある場合はボタンを並べる。
　→このパターンなし
